question_data = [

                 {"category": "Science: Computers",
                                      "type": "boolean",
                                      "difficulty": "easy",
                                      "question": "RAM stands for Random Access Memory.",
                                      "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                      "question": "Salt is 100% composed of Sodium.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                      "question": "Denmark has a monarch.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "easy",
                                      "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The shotgun appears in every numbered Resident Evil game.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}
                                     ]

